In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [20]:
df = pd.read_csv("winequalityN.csv")

In [21]:
df.head()

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0  white            7.0              0.27         0.36            20.7   
1  white            6.3              0.30         0.34             1.6   
2  white            8.1              0.28         0.40             6.9   
3  white            7.2              0.23         0.32             8.5   
4  white            7.2              0.23         0.32             8.5   

   chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0      0.045                 45.0                 170.0   1.0010  3.00   
1      0.049                 14.0                 132.0   0.9940  3.30   
2      0.050                 30.0                  97.0   0.9951  3.26   
3      0.058                 47.0                 186.0   0.9956  3.19   
4      0.058                 47.0                 186.0   0.9956  3.19   

   sulphates  alcohol  quality  
0       0.45      8.8        6  
1       0.49      9.5        6  
2       0.44     10.1        6  
3       0.40      9.9        6  
4       0.40      9.9        6

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   type                  6497 non-null   object 
 1   fixed acidity         6487 non-null   float64
 2   volatile acidity      6489 non-null   float64
 3   citric acid           6494 non-null   float64
 4   residual sugar        6495 non-null   float64
 5   chlorides             6495 non-null   float64
 6   free sulfur dioxide   6497 non-null   float64
 7   total sulfur dioxide  6497 non-null   float64
 8   density               6497 non-null   float64
 9   pH                    6488 non-null   float64
 10  sulphates             6493 non-null   float64
 11  alcohol               6497 non-null   float64
 12  quality               6497 non-null   int64  
dtypes: float64(11), int64(1), object(1)
memory usage: 660.0+ KB


In [23]:
df.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    6487.000000       6489.000000  6494.000000     6495.000000   
mean        7.216579          0.339691     0.318722        5.444326   
std         1.296750          0.164649     0.145265        4.758125   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.400000          0.230000     0.250000        1.800000   
50%         7.000000          0.290000     0.310000        3.000000   
75%         7.700000          0.400000     0.390000        8.100000   
max        15.900000          1.580000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  6495.000000          6497.000000           6497.000000  6497.000000   
mean      0.056042            30.525319            115.744574     0.994697   
std       0.035036            17.749400             56.521855     0.002999   
min       0.009000             1.000000              6.000000     0.987110   
25%       0.038000            17.000000             77.000000     0.992340   
50%       0.047000            29.000000            118.000000     0.994890   
75%       0.065000            41.000000            156.000000     0.996990   
max       0.611000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  6488.000000  6493.000000  6497.000000  6497.000000  
mean      3.218395     0.531215    10.491801     5.818378  
std       0.160748     0.148814     1.192712     0.873255  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.110000     0.430000     9.500000     5.000000  
50%       3.210000     0.510000    10.300000     6.000000  
75%       3.320000     0.600000    11.300000     6.000000  
max       4.010000     2.000000    14.900000     9.000000

In [25]:
df.columns


Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [68]:
df.shape

(6497, 13)

In [69]:
df.fillna(1, inplace=True)

# Get Unique Values

In [70]:
df.replace({'type':{'white' : 0,'red':1}},inplace=True)

In [71]:
df[['type']].value_counts()

type
0       4898
1       1599
dtype: int64

In [72]:
df['quality'].value_counts()

6    2836
5    2138
7    1079
4     216
8     193
3      30
9       5
Name: quality, dtype: int64

In [73]:
df.groupby('quality').mean()

type  fixed acidity  volatile acidity  citric acid  \
quality                                                           
3        0.333333       7.853333          0.517000     0.281000   
4        0.245370       7.288889          0.457963     0.272315   
5        0.318522       7.314546          0.390339     0.308045   
6        0.224965       7.169323          0.314699     0.324263   
7        0.184430       7.128962          0.290213     0.334764   
8        0.093264       6.808290          0.291010     0.332539   
9        0.000000       7.420000          0.298000     0.386000   

         residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  \
quality                                                                         
3              5.140000   0.077033            39.216667            122.033333   
4              4.153704   0.064509            20.636574            103.432870   
5              5.804116   0.064666            30.237371            120.839102   
6              5.549577   0.054501            31.165021            115.410790   
7              4.730491   0.045272            30.422150            108.498610   
8              5.382902   0.041124            34.533679            117.518135   
9              4.120000   0.027400            33.400000            116.000000   

          density        pH  sulphates    alcohol  
quality                                            
3        0.995744  3.257667   0.506333  10.215000  
4        0.994833  3.231620   0.507176  10.180093  
5        0.995849  3.208938   0.526637   9.837783  
6        0.994558  3.214573   0.532796  10.587553  
7        0.993126  3.223661   0.547025  11.386006  
8        0.992514  3.223212   0.512487  11.678756  
9        0.991460  3.308000   0.466000  12.180000

# Define Y and X

In [74]:
y=df['quality']

In [75]:
y

0       6
1       6
2       6
3       6
4       6
       ..
6492    5
6493    6
6494    6
6495    5
6496    6
Name: quality, Length: 6497, dtype: int64

In [76]:
y.shape

(6497,)

In [77]:
X = df[['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality']]

In [78]:
X.shape

(6497, 13)

In [79]:
X

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
0        0            7.0             0.270         0.36            20.7   
1        0            6.3             0.300         0.34             1.6   
2        0            8.1             0.280         0.40             6.9   
3        0            7.2             0.230         0.32             8.5   
4        0            7.2             0.230         0.32             8.5   
...    ...            ...               ...          ...             ...   
6492     1            6.2             0.600         0.08             2.0   
6493     1            5.9             0.550         0.10             2.2   
6494     1            6.3             0.510         0.13             2.3   
6495     1            5.9             0.645         0.12             2.0   
6496     1            6.0             0.310         0.47             3.6   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
0         0.045                 45.0                 170.0  1.00100  3.00   
1         0.049                 14.0                 132.0  0.99400  3.30   
2         0.050                 30.0                  97.0  0.99510  3.26   
3         0.058                 47.0                 186.0  0.99560  3.19   
4         0.058                 47.0                 186.0  0.99560  3.19   
...         ...                  ...                   ...      ...   ...   
6492      0.090                 32.0                  44.0  0.99490  3.45   
6493      0.062                 39.0                  51.0  0.99512  3.52   
6494      0.076                 29.0                  40.0  0.99574  3.42   
6495      0.075                 32.0                  44.0  0.99547  3.57   
6496      0.067                 18.0                  42.0  0.99549  3.39   

      sulphates  alcohol  quality  
0          0.45      8.8        6  
1          0.49      9.5        6  
2          0.44     10.1        6  
3          0.40      9.9        6  
4          0.40      9.9        6  
...         ...      ...      ...  
6492       0.58     10.5        5  
6493       1.00     11.2        6  
6494       0.75     11.0        6  
6495       0.71     10.2        5  
6496       0.66     11.0        6  

[6497 rows x 13 columns]

# Get X Variable Standardize

In [80]:
from sklearn.preprocessing import StandardScaler

In [81]:
ss = StandardScaler()

In [82]:
X = ss.fit_transform(X)

In [83]:
X

array([[-0.57136659, -0.15702014, -0.42432349, ..., -0.54623297,
        -1.41855821,  0.20799905],
       [-0.57136659, -0.6879781 , -0.24377075, ..., -0.27815557,
        -0.83161516,  0.20799905],
       [-0.57136659,  0.67734236, -0.36413924, ..., -0.61325232,
        -0.32852111,  0.20799905],
       ...,
       [ 1.75018984, -0.6879781 ,  1.02009844, ...,  1.4643475 ,
         0.42611996,  0.20799905],
       [ 1.75018984, -0.99138264,  1.83258578, ...,  1.19627011,
        -0.2446721 , -0.93722961],
       [ 1.75018984, -0.91553151, -0.1835865 , ...,  0.86117336,
         0.42611996,  0.20799905]])

# Splitting & Training

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.3,random_state=2529)

In [86]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1949, 13), (4548, 13), (1949,), (4548,))

# Model train

In [87]:
from sklearn.svm import SVC

In [88]:
svc = SVC()

In [89]:
svc.fit(X_train,y_train)

SVC()

# Model prediction

In [90]:
y_pred = svc.predict(X_test)

In [91]:
y_pred.shape

(4548,)

In [93]:
y_pred

array([6, 6, 5, ..., 6, 5, 5], dtype=int64)

In [94]:
from sklearn.metrics import confusion_matrix,classification_report

In [95]:
print(confusion_matrix(y_test,y_pred))

[[   0   15    6    0    0    0    0]
 [   0  141   10    0    0    0    0]
 [   0    0 1482    6    0    0    0]
 [   0    0    5 1984    0    0    0]
 [   0    0    0   11  748    0    0]
 [   0    0    1    0    7  130    0]
 [   0    0    0    0    0    2    0]]


In [96]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00        21
           4       0.90      0.93      0.92       151
           5       0.99      1.00      0.99      1488
           6       0.99      1.00      0.99      1989
           7       0.99      0.99      0.99       759
           8       0.98      0.94      0.96       138
           9       0.00      0.00      0.00         2

    accuracy                           0.99      4548
   macro avg       0.69      0.69      0.69      4548
weighted avg       0.98      0.99      0.98      4548



C:\Users\yash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\yash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\yash\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Rerun with two class created for Wine  quality

In [99]:
y =df['quality'].apply(lambda y_value: 1 if y_value>=6 else 0)

In [103]:
y.value_counts()

1    4113
0    2384
Name: quality, dtype: int64

# Splitting & Training

In [104]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.3,random_state=2529)

X_train.shape,X_test.shape,y_train.shape,y_test.shape

((1949, 13), (4548, 13), (1949,), (4548,))

# Train Model 

In [105]:
from sklearn.svm import SVC

In [106]:
svc = SVC()

In [107]:
svc.fit(X_train,y_train)

SVC()

# Model prediction

In [108]:
y_pred = svc.predict(X_test)

In [110]:
y_pred.shape

(4548,)

In [113]:
y_pred

array([1, 1, 0, ..., 1, 0, 0], dtype=int64)

# Model Evaluation

In [114]:
from sklearn.metrics import confusion_matrix,classification_report

In [115]:
print(confusion_matrix(y_test,y_pred))

[[1658    2]
 [   9 2879]]


In [116]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      1660
           1       1.00      1.00      1.00      2888

    accuracy                           1.00      4548
   macro avg       1.00      1.00      1.00      4548
weighted avg       1.00      1.00      1.00      4548



# Future Prediction

In [117]:
X_new= df.sample(1)
X_new

type  fixed acidity  volatile acidity  citric acid  residual sugar  \
2762     0            7.3              0.32         0.35             1.4   

      chlorides  free sulfur dioxide  total sulfur dioxide  density    pH  \
2762       0.05                  8.0                 163.0  0.99244  3.24   

      sulphates  alcohol  quality  
2762       0.42     10.7        5

In [118]:
X_new.shape

(1, 13)

In [119]:
X_new = ss.fit_transform(X_new)

In [120]:
y_pred_new = svc.predict(X_new ) 

In [121]:
y_pred_new

array([1], dtype=int64)