In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [2]:
df = pd.read_csv("Womens Clothing E-Commerce Reviews.csv")
df.head()

ID  Clothing ID  Age                    Title  \
0   0          767   33                      NaN   
1   1         1080   34                      NaN   
2   2         1077   60  Some major design flaws   
3   3         1049   50         My favorite buy!   
4   4          847   47         Flattering shirt   

                                         Review Text  Rating  Recommended IND  \
0  Absolutely wonderful - silky and sexy and comf...       4                1   
1  Love this dress!  it's sooo pretty.  i happene...       5                1   
2  I had such high hopes for this dress and reall...       3                0   
3  I love, love, love this jumpsuit. it's fun, fl...       5                1   
4  This shirt is very flattering to all due to th...       5                1   

   Positive Feedback Count   Division Name Department Name Class Name  
0                        0       Initmates        Intimate  Intimates  
1                        4         General         Dresses    Dresses  
2                        0         General         Dresses    Dresses  
3                        0  General Petite         Bottoms      Pants  
4                        6         General            Tops    Blouses

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23486 entries, 0 to 23485
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       23486 non-null  int64 
 1   Clothing ID              23486 non-null  int64 
 2   Age                      23486 non-null  int64 
 3   Title                    19676 non-null  object
 4   Review Text              22641 non-null  object
 5   Rating                   23486 non-null  int64 
 6   Recommended IND          23486 non-null  int64 
 7   Positive Feedback Count  23486 non-null  int64 
 8   Division Name            23472 non-null  object
 9   Department Name          23472 non-null  object
 10  Class Name               23472 non-null  object
dtypes: int64(6), object(5)
memory usage: 2.0+ MB


In [4]:
df.shape

(23486, 11)

# Misssing Values

In [5]:
df.isna().sum()

ID                            0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                 845
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [6]:
df[df['Review Text']==""]=np.NaN

In [7]:
df['Review Text'].fillna("No Review",inplace=True)

In [8]:
df.isnull().sum()

ID                            0
Clothing ID                   0
Age                           0
Title                      3810
Review Text                   0
Rating                        0
Recommended IND               0
Positive Feedback Count       0
Division Name                14
Department Name              14
Class Name                   14
dtype: int64

In [9]:
df['Review Text']

0        Absolutely wonderful - silky and sexy and comf...
1        Love this dress!  it's sooo pretty.  i happene...
2        I had such high hopes for this dress and reall...
3        I love, love, love this jumpsuit. it's fun, fl...
4        This shirt is very flattering to all due to th...
                               ...                        
23481    I was very happy to snag this dress at such a ...
23482    It reminds me of maternity clothes. soft, stre...
23483    This fit well, but the top was very see throug...
23484    I bought this dress for a wedding i have this ...
23485    This dress in a lovely platinum is feminine an...
Name: Review Text, Length: 23486, dtype: object

# Define target Y & Feature X

In [10]:
df.columns

Index(['ID', 'Clothing ID', 'Age', 'Title', 'Review Text', 'Rating',
       'Recommended IND', 'Positive Feedback Count', 'Division Name',
       'Department Name', 'Class Name'],
      dtype='object')

In [11]:
X=df['Review Text']

In [12]:
y=df['Rating']

In [13]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

# Train test Split

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.3,random_state=2529)

In [16]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
 cv= CountVectorizer(lowercase = True, analyzer = 'word',ngram_range=(2,3),stop_words ='english',max_features=5000)   

In [19]:
X_train= cv.fit_transform(X_train)

In [20]:
cv.get_feature_names_out()

array(['00 petite', '0p fit', '10 12', ..., 'years come', 'yellow color',
       'yoga pants'], dtype=object)

In [21]:
X_train.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [22]:
X_test = cv.fit_transform(X_test)

In [23]:
cv.get_feature_names_out()

array(['00p 0p', '10 12', '10 bought', ..., 'years come', 'years old',
       'yoga pants'], dtype=object)

In [24]:
X_test.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

# Get Model Train

In [27]:
from sklearn.naive_bayes import MultinomialNB

In [28]:
model = MultinomialNB()


In [29]:
model.fit(X_train,y_train)


MultinomialNB()

# Get model Prediction

In [31]:

y_pred = model.predict(X_test)

In [33]:
y_pred.shape


(16441,)

In [34]:
y_pred

array([2., 3., 3., ..., 5., 3., 2.])

# Get Probability of Each Predicted Class

In [36]:
model.predict_proba(X_test)

array([[4.29091190e-02, 8.05387425e-01, 2.72387528e-02, 1.06772810e-01,
        1.76918929e-02],
       [4.46730941e-02, 5.95612569e-02, 5.66250732e-01, 1.71242189e-01,
        1.58272728e-01],
       [2.51248832e-01, 7.55692656e-02, 2.83267813e-01, 2.33406013e-01,
        1.56508077e-01],
       ...,
       [8.88242969e-02, 3.56214559e-02, 1.25180006e-01, 3.97846465e-02,
        7.10589594e-01],
       [4.52704317e-02, 1.43533257e-01, 7.46569164e-01, 4.83729229e-02,
        1.62542243e-02],
       [7.44167759e-02, 7.07831699e-01, 1.53403856e-02, 2.01947266e-01,
        4.63873946e-04]])

# Get Model Evaluation

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
print(confusion_matrix(y_test,y_pred))

[[  30   57  126  106  278]
 [  77  132  213  202  446]
 [ 161  270  406  361  801]
 [ 312  452  578  689 1539]
 [ 739 1047 1112 1646 4661]]


In [39]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.05      0.03       597
         2.0       0.07      0.12      0.09      1070
         3.0       0.17      0.20      0.18      1999
         4.0       0.23      0.19      0.21      3570
         5.0       0.60      0.51      0.55      9205

    accuracy                           0.36     16441
   macro avg       0.22      0.22      0.21     16441
weighted avg       0.41      0.36      0.38     16441



# Recatogarize Ratings

In [41]:
df['Rating'].value_counts()

5.0    13131
4.0     5077
3.0     2871
2.0     1565
1.0      842
Name: Rating, dtype: int64

In [42]:
df.replace({'Rating':{ '1' : 0,'2':0,'3':0,'4':1,'5':1}},inplace=True)

In [44]:
y= df['Rating']

In [48]:
x= df['Review Text']

# Splitting & Training

In [49]:
from sklearn.model_selection import train_test_split

In [50]:
X_train,X_test,y_train,y_test = train_test_split(X,y, train_size = 0.3,random_state=2529)

In [51]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((7045,), (16441,), (7045,), (16441,))

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [57]:
cv = CountVectorizer(lowercase = True,analyzer ='word',ngram_range=(2,3),stop_words ='english',max_features=5000)

In [58]:
X_train = cv.fit_transform(X_train)

In [60]:
X_test = cv.fit_transform(X_test)

# Get Model RE-Train

In [61]:
from sklearn.naive_bayes import MultinomialNB

In [62]:
model = MultinomialNB()

In [63]:
model.fit(X_train,y_train)

MultinomialNB()

# Get model Prediction

In [65]:
y_pred = model.predict(X_test)

In [66]:
y_pred.shape

(16441,)

In [67]:
y_pred

array([2., 3., 3., ..., 5., 3., 2.])

# Model Evaluation

In [68]:
from sklearn.metrics import mean_absolute_error,mean_absolute_percentage_error,confusion_matrix,classification_report

In [69]:
mean_absolute_error(y_test,y_pred)

1.2316769052977312

In [70]:
mean_absolute_percentage_error(y_test,y_pred)

0.40078563753218577

In [71]:
print(confusion_matrix(y_test,y_pred))

[[  30   57  126  106  278]
 [  77  132  213  202  446]
 [ 161  270  406  361  801]
 [ 312  452  578  689 1539]
 [ 739 1047 1112 1646 4661]]


In [72]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         1.0       0.02      0.05      0.03       597
         2.0       0.07      0.12      0.09      1070
         3.0       0.17      0.20      0.18      1999
         4.0       0.23      0.19      0.21      3570
         5.0       0.60      0.51      0.55      9205

    accuracy                           0.36     16441
   macro avg       0.22      0.22      0.21     16441
weighted avg       0.41      0.36      0.38     16441

